name: super_ranges
description: Powerful yet intuitive Ranges for dart. Open, closed, reversed and by steps ranges.
version: 1.3.0+1
author: "Daniel Illescas Romero <illescas.daniel@protonmail.com>"
homepage: https://github.com/illescasDaniel
repository: https://github.com/illescasDaniel/Super_Ranges

environment:
  sdk: ">=2.1.0 <3.0.0"

# super_ranges also works without flutter
#dev_dependencies:
#  test: ^1.6.4
dev_dependencies:
  flutter_test:
    sdk: flutter
